apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
stringData:
  DB_USERNAME: yourdbuser
  DB_PASSWORD: yourdbpassword
  STRIPE_KEY: yourstripekey
  TWILIO_SID: yourtwiliosid
  TWILIO_AUTH_TOKEN: yourtwilioauthtoken